//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cych.org.tw/", ConfigurationName="ADWebService.AdUserIdentifySoap")]
    public interface AdUserIdentifySoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cych.org.tw/Verify", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Verify(string UserId, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cych.org.tw/Verify", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> VerifyAsync(string UserId, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cych.org.tw/VerifyUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool VerifyUser(string UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cych.org.tw/VerifyUser", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> VerifyUserAsync(string UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cych.org.tw/IsEmpUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsEmpUser(string UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cych.org.tw/IsEmpUser", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsEmpUserAsync(string UserId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface AdUserIdentifySoapChannel : ADWebService.AdUserIdentifySoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class AdUserIdentifySoapClient : System.ServiceModel.ClientBase<ADWebService.AdUserIdentifySoap>, ADWebService.AdUserIdentifySoap
    {
        
        /// <summary>
        /// 實作此部分方法來設定服務端點。
        /// </summary>
        /// <param name="serviceEndpoint">要設定的端點</param>
        /// <param name="clientCredentials">用戶端認證</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AdUserIdentifySoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AdUserIdentifySoapClient.GetBindingForEndpoint(endpointConfiguration), AdUserIdentifySoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AdUserIdentifySoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AdUserIdentifySoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AdUserIdentifySoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AdUserIdentifySoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AdUserIdentifySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool Verify(string UserId, string Pwd)
        {
            return base.Channel.Verify(UserId, Pwd);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyAsync(string UserId, string Pwd)
        {
            return base.Channel.VerifyAsync(UserId, Pwd);
        }
        
        public bool VerifyUser(string UserId)
        {
            return base.Channel.VerifyUser(UserId);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyUserAsync(string UserId)
        {
            return base.Channel.VerifyUserAsync(UserId);
        }
        
        public bool IsEmpUser(string UserId)
        {
            return base.Channel.IsEmpUser(UserId);
        }
        
        public System.Threading.Tasks.Task<bool> IsEmpUserAsync(string UserId)
        {
            return base.Channel.IsEmpUserAsync(UserId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AdUserIdentifySoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AdUserIdentifySoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AdUserIdentifySoap))
            {
                return new System.ServiceModel.EndpointAddress("http://webf.cych.org.tw/WebTeam/UserIdentify/Authenticate.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AdUserIdentifySoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://webf.cych.org.tw/WebTeam/UserIdentify/Authenticate.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AdUserIdentifySoap,
            
            AdUserIdentifySoap12,
        }
    }
}
